### ISSUE TITLE
How to setup the example with http?

### ISSUE THREAD

**Issue by landall** [krizalys/onedrive-php-sdk#45]
I cannot add a http redirect url in my application management page of microsoft account...
how to setup it? I cannot use https in that server.

**Comment by krizalys** [comment]
Hi @landall, thanks for your interest.

Unfortunately, there's not much I can do to relax Microsoft's requirements.
As I remember, it also works with `localhost` and no HTTPS (did not try it recently).

Also, if SSL setup is a problem because of the cost, did you consider Letsencrypt? The provide free certificates and support a bunch of web servers with almost no set up. For more details, please see: https://letsencrypt.org/

Let me if these do not solve your problem.

**Comment by landall** [comment]
thx for ur reply. My server is running behind a firewall and only port 80 goes through. i am trying another way to solve it.
