### ISSUE TITLE
Problem uploading larger file

### ISSUE THREAD

**Issue by sodevrom** [krizalys/onedrive-php-sdk#47]
Hello 
 Awesome library, I thank you for it :)
 I have a problem. When I upload a larger file, I get this:
Severity: Error --> Allowed memory size of 268435456 bytes exhausted (tried to allocate 115351552 bytes) /home/onlblcm/dev.blasteronline.com/application/libraries/onedrive-php-sdk-master/src/Krizalys/Onedrive/Client.php 791

 How can this be fixed?
 Can the file be split or what can I do?

 Thanks
 Vlad

**Comment by sodevrom** [comment]
Currently I am using it like this:
$data = file_get_contents($file);
$channelDir->createFile($name, $data);

 But the fwrite is giving me error of allowed memory size. What would be the best way to do this? TO upload a large file avoiding the memory limit?

**Comment by krizalys** [comment]
Hi @sodevrom, thanks for your feedback.

By default, file uploads are backed by memory streams, for better performance. But if the file is big, it could hit PHP's `memory_limit` and lead to this kind of error.

A solution which could fix your issue is to try file uploads backed by temporary files. To do this, you need to set the `Client`' `stream_back_end` constructor option to `StreamBackEnd::TEMP`, when you instantiate the `Client`, like this:

```php
$yourClient = new \Krizalys\Onedrive\Client([
    // your client ID & other options
    'stream_back_end' => \Krizalys\Onedrive\StreamBackEnd::TEMP
]);
```

Please be warned that uploading large files is experimental in the current version and I've received reports that it's not stable on some systems/PHP configurations/cURL versions. Please let know if the above solution fixes your issue.

With that being said, I'm about to launch the version 2 of this library, which switched to the official Microsoft Graph client to interact with Onedrive. Hopefully, this would make file uploads more stable.

**Comment by krizalys** [comment]
This feature is supported up to version `1.2`: https://github.com/krizalys/onedrive-php-sdk/blob/1.2.0/src/Krizalys/Onedrive/StreamBackEnd.php - in version 2 (current version), this method has been discontinued and removed though your use case should still be addressed.

I propose that:

1. You upgrade to version 2 since Microsoft discontinued the API required by version 1
2. You use this API to upload files: https://github.com/krizalys/onedrive-php-sdk/blob/master/src/Proxy/DriveItemProxy.php#L270 (for big files, try passing them as PHP streams), here is an example with a memory-backed stream: https://github.com/krizalys/onedrive-php-sdk/blob/master/test/functional/KrizalysOnedriveTest.php#L288-L294 - please adapt it to use a file-backed stream, as suggested before

If you still have issues with big files in version 2, please kindly reopen this issue.

**Comment by krizalys** [comment]
This endpoint supports files up to 4 MB only (source: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_put_content?view=odsp-graph-online).

To upload bigger files, we need to write support for resumable file uploads (ref: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online). This is planned here: https://github.com/krizalys/onedrive-php-sdk/issues/33

If you need this urgently, consider proposing a PR for it.
