### ISSUE TITLE
Handling Large File Uploads (Example/Support Request)

### ISSUE THREAD

**Issue by solepixel** [krizalys/onedrive-php-sdk#66]
Hi! Thanks again for all the work on this library. I'm trying to find an example of how to best use the `startUpload()` method and the `UploadSessionProxy` object. Excuse my ignorance, but does this work "automagically" or do I need to monitor progress, resume upload, detect completion, etc? The only example I could find was:

```php
$uploadSession1 = $driveItem->startUpload(
    'file.txt',
    'Some other content',
    [
        'conflictBehavior' => ConflictBehavior::RENAME,
        'type'             => 'text/plain',
    ]
);

$childDriveItem = $uploadSession1->complete();
```

My questions are:

1. Should 'type' be 'contentType'? I've seen both used and wondered which is correct.
2. Is `file_get_contents( $path_to_file_being_uploaded )` an acceptable value for the 2nd parameter ($content)? There are some other open tickets/support mentioning a Stream should be used. Do you have an example for that? Is that better?
3. What is the behavior of `$uploadSession1->complete()`? Is this a value that should be stored, and used again when resuming an incomplete upload? How can I tell when it's finished and/or if it was successful? The documentation isn't clear on how to get this information. It only appears to return a `DriveItemProxy` or throw an exception.

I'm mostly looking for a thorough example on how to use `startUpload()`.

Lastly, is it safe to ALWAYS use `startUpload()` vs just using `upload()` if the file is smaller and can be uploaded via a single upload session?

Thanks!

**Comment by krizalys** [comment]
> Excuse my ignorance, but does this work "automagically" or do I need to monitor progress, resume upload, detect completion, etc?

You need to call `complete()` on the `UploadSessionProxy` instance. `complete()` works "automagically". It is a synchronous operation - completion is signaled when the function returns. Progress monitoring/resuming upload are not supported.


> 1. Should 'type' be 'contentType'? I've seen both used and wondered which is correct.

Unfortunately, neither `type` and `contentType` seem to have any effect currently, you can omit both. From my observations, OneDrive uses the suffix of the file name to determine its type.


> 2. Is `file_get_contents( $path_to_file_being_uploaded )` an acceptable value for the 2nd parameter ($content)? There are some other open tickets/support mentioning a Stream should be used. Do you have an example for that? Is that better?

Yes, `file_get_contents(...)` is an acceptable value since it normally returns a string. 
This function puts the whole file content in memory though, so watch out for memory usage.

Streams also work and are designed for better memory usage, they are a better fit for big files. Here is an example using a PHP built-in stream: https://github.com/krizalys/onedrive-php-sdk/blob/2.5.1/test/functional/Proxy/DriveItemProxyTest.php#L537-L549

Therefore, yes, using a stream is probably better in most cases.


> 3. What is the behavior of `$uploadSession1->complete()`? Is this a value that should be stored, and used again when resuming an incomplete upload? How can I tell when it's finished and/or if it was successful? The documentation isn't clear on how to get this information. It only appears to return a `DriveItemProxy` or throw an exception.

`$uploadSession1->complete()` runs a loop which uploads the file in chunks.

The value returned does not allow you to retry - retrying is not supported.

As a synchronous function, it blocks until the operation is complete. Completion & success is signaled by the fact that the function returned without throwing an exception. The `DriveItemProxy` returned can be queried as any `DriveItemProxy`.


> Lastly, is it safe to ALWAYS use `startUpload()` vs just using `upload()` if the file is smaller and can be uploaded via a single upload session?

Yes, `startUpload()` is safe and works with any file, even small ones.

`upload()` works only with small files (< 4 MB), it is here more for testing purposes, simple applications, special cases where streams are impractical.


Please feel free to reopen if you have more questions.

**Comment by solepixel** [comment]
@krizalys Thanks for the detailed response! Everything makes sense except for the stream. Unfortunately I'm just not grasping the concept. Would this be how you would use a stream:

```php
$stream = fopen( 'php://memory', 'rb+' );
fwrite( $stream, file_get_contents( $path_to_file_being_uploaded ) );
rewind( $stream );

$upload = $folder->startUpload( basename( $path_to_file_being_uploaded ), $stream, $args );
```

I just want to make sure I'm not putting it in memory because large files will be an issue.

**Comment by krizalys** [comment]
@solepixel Since `fopen()` already returns a stream, you can simply write:

```php
$stream = fopen($path_to_file_being_uploaded, 'rb' );
$upload = $folder->startUpload(basename($path_to_file_being_uploaded), $stream, $args);
```

The previous example was from a test case where I chose not to have a physical file to read from, hence the trick using a memory stream, filling up with dummy data, and rewinding it :)

**Comment by solepixel** [comment]
Thanks for the explanation!

**Comment by karinnahmay** [comment]
@krizalys hi, this actually worked but i got ~tmpxxx file created inside my folder. How can i get rid of that? 
i used this exact code:

$stream = fopen($path_to_file_being_uploaded, 'rb');
$upload = $folder->startUpload(basename($path_to_file_being_uploaded), $stream, $args);

Thanks!

**Comment by krizalys** [comment]
@karinnahmay This could be the result of your PHP configuration. In some cases, memory streams are backed by temporary files. In some other cases, this kind of files are created when reading files uploaded from a browser via a web form.

For more details on these, please look into the relevant pages of PHP documentation:

- https://www.php.net/manual/en/wrappers.php.php
- https://www.php.net/manual/en/features.file-upload.php

Let me know more details if you could not find an answer there.
