### ISSUE TITLE
Redirect login without login page

### ISSUE THREAD

**Issue by karinnahmay** [krizalys/onedrive-php-sdk#67]
Hi @krizalys , lame question here but i am really confused on how to implement your code without login in. I am working with sites to upload into my onedrive business app and i dont want them to login using my credentials. Can you help me with this please.

I have this short script but authentication is not working, i was basing this on the example testing you made. https://prnt.sc/ps1mh3 

Thanks!

**Comment by tudders** [comment]
Hi Karinnahmay.

This is mine (which works). 

// Gets a log in URL with sufficient privileges from the OneDrive API.
$url = $client->getLogInUrl([
    //'files.read',
    //'files.read.all',
    //'files.readwrite',
    'files.readwrite.all',
    'Files.ReadWrite.AppFolder',
    'offline_access',
], $config['ONEDRIVE_REDIRECT_URI']);

// Persist the OneDrive client' state for next API requests.
$_SESSION['onedrive.client.state'] = $client->getState();

// Redirect the user to the login page.

echo '<script> window.location = "' . $url .  '"; </script>';

Note the redirect to the onedrive login page.

You should also have provided a return page which is used to collect and store the access token that associates your app to the users onedrive. You use this token on subsequent calls without requiring further auth from the user.

**Comment by krizalys** [comment]
Hi @karinnahmay, the example provided by @tudders should work. Thanks for sharing it @tudders.
I believe you have got the `authenticate` function from some functional test in this library, it is probably not exactly what you need since it relies on some webdriver-automated browser for testing purposes (see below).

Note that it is the nature of the OAuth protocol (used by OneDrive API) to require the user to log in and give your app the permissions it requested. From what I have observed, logging in works only when using a real web browser and is hardly done programmatically - hence the use of webdriver in the tests.

However, if you pass the `offline_access` scope, as shown by @tudders in their example, you will be able to refresh the token using `Client::renewAccessToken()` without having the user to log in again. Perhaps you have a way to design your application in a way that the user would have to log in once and then you would store their token in some database for long term persistency, and renew/update your database anytime it gets expired?

I will post a more complete example to show how you can renew a token this week-end.

**Comment by krizalys** [comment]
Hi @karinnahmay, here is an (untested) example of how you can restrict the number of log in to OneDrive to one:

`index.php`:

```php
// Gets your user ID in $userId somehow - note that this ID has nothing to do
// with the OneDrive user ID and would be maintained in your own user table

$rows = executeSql("SELECT state FROM onedrive_state WHERE user_id = $user_id");

// User never logged in to OneDrive via your app - let them do so and persist
// their state in your DB
// This is the only time the user would need to log in to OneDeive - afterwards
// the token will always be coming from your DB, and refreshed when it expires
if (empty($rows)) {
    $client = Onedrive::client('YOUR_ONEDRIVE_CLIENT_ID');

    $url = $client->getLogInUrl([
        'offline_access', // This is required for renewing tokens
        // ...
    ], 'index.php');

    $state = $client->getState();
    $stateJson = json_encode($state);
    executeSql("INSERT INTO onedrive_state(user_id, state) VALUES ($userId, $stateJson)");
    header('HTTP/1.1 302 Found', true, 302);
    header("Location: $url");
    exit 0;
}

// User previously logged in to Onedrive via your app - you either need to
// finalize the authentication by obtaining a token and persisting in your DB,
// or renew the it if it has expired and update it in your DB
$state = json_decode($rows[0]->state);
$client = Onedrive::client('YOUR_ONEDRIVE_CLIENT_ID', ['state' => $rows[0]->state]);

// If you get called with a code in the URL, the user was just redirected from
// OneDrive after you redirected them here to let them log in - you are now
// finalizing the authentication by getting an access token and updating the
// state in your DB
if ($_GET['code']) {
    $client->obtainAccessToken('YOUR_ONEDRIVE_CLIENT_SECRET', $_GET['code']);
    $state = $client->getState();
    $stateJson = json_encode($state);
    executeSql("UPDATE onedrive_state SET state = '$stateJson' WHERE user_id = $userId)");

// Otherwise, you need to check if the token you have in your records in still
// valid and renew it if not - the state also needs to be updated in your DB so
// the token shows as valid for a little while
} else {
    $tokenObtainTime = $state->token->obtained;
    $tokenExpirationTime = timeAdd(time(), $state->token->expires_in);

    if (timeCompare($tokenObtainTime, $tokenExpirationTime, '<=')) {
        $client->renewAccessToken('YOUR_ONEDRIVE_SECRET');
        $state = $client->getState();
        $stateJson = json_encode($state);
        executeSql("UPDATE onedrive_state SET state = '$stateJson' WHERE user_id = $userId)");
    }
}

// You can now use the client
$file = $client->getRoot()->upload('hello.txt', 'Hello World!');
echo $file->download();
// => Hello World!
```

As you can see, I'm making some assumptions here, including that you are using some SQL database to persist users/OneDrive states for your users. Some functions are just imaginary but should be self-explanatory. Please adjust as needed.

Show me more code if this does not work.

**Comment by karinnahmay** [comment]
Hi @krizalys, yes finally its working okay now. Thanks for that. But i still got one question. How can upload multiple sub folders in one run and it is possible to check one time if the subfolders exists? Example:

test/sub1/sub2/ where sub2 is the location where i want to upload my files but first i still need to check if this path exist. 

please help. thanks!

**Comment by krizalys** [comment]
@karinnahmay I'm afraid you cannot do all of this in a single call with the current version.

You app would need to combine recursive calls to `Client::getDriveItemByPath()` - to check for paths existence - and `Client::createFolder()` - to create them when they are missing. While retrieving/creating each folder, you get the `DriveItem` (folder) on which you can upload the files it contain one by one, using `Client::upload()`.

**Comment by karinnahmay** [comment]
Thanks @krizalys sorry to bother you but still one last question: When i get the AccessTokenStatus its always 0, why is this? i am getting the status to know if i should renew the token. Thanks in advance!

**Comment by karinnahmay** [comment]
Thanks @krizalys! cheers!

**Comment by Artem2710** [comment]
> Hi @krizalys , lame question here but i am really confused on how to implement your code without login in. I am working with sites to upload into my onedrive business app and i dont want them to login using my credentials. Can you help me with this please.
> 
> I have this short script but authentication is not working, i was basing this on the example testing you made. https://prnt.sc/ps1mh3
> 
> Thanks!

Is there any code example how to make authorization without visualization in the browser? Very grateful.

**Comment by krizalys** [comment]
@Artem2710 OAuth is designed specifically to allow users to delegate to tiers access to their accounts without giving their credentials to those tiers. If you are unfamiliar with OAuth, there is a good summary here: https://medium.com/@somindagamage/oauth-2-0-for-dummies-8807cff5c3b2

Please understand that **the whole idea is not to annoy your users, but rather, to build trust between them and you application** - ie. when asked to give their credentials, your users may trust a reputable company (Microsoft) more than your application. This is why OAuth specifically requires authentication to be handled exclusively by the provider (Microsoft).

With that being said, there are ways to work around it, all with some drawbacks:

1. you can following the example design I have shown above - the best solution because it is a use case supported by OAuth, but users still need to log in to Microsoft at least once
2. you can automate a headless web browser to perform the authorization without visual feedback, as show in the functional tests - not recommended on production due to the unreliability of browser automation
3. instead of a full-blown web browser, you can theoretically perform the authorization using a lower-level HTTP client, such as curl, by sending carefully-crafted requests to the authorization server and reacting to responses appropriately - not sure if it's even possible, but it is probably as unreliable as the above

**Please be warned that using 2 and 3 in a way that involves your users disclosing their credentials to your application defeats the purposes of OAuth. It may even be a violation of Microsoft terms of service.**
