### ISSUE TITLE
Client error: 400 Bad Request obtainAccessToken

### ISSUE THREAD

**Issue by davemaxg** [krizalys/onedrive-php-sdk#87]
Hi,

I'm getting the following error when trying to obtainAccessToken
GuzzleHttp\Exception\ClientException: Client error: `POST https://login.microsoftonline.com/common/oauth2/v2.0/token` resulted in a `400 Bad Request` response: {"error":"invalid_scope","error_description":"AADSTS70011: The provided request must include a 'scope' input parameter.\ (truncated...) in GuzzleHttp\Exception\RequestException::create() (line 113 of /code/sites/all/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php).

If I modify obtainAccessToken to include a scope with my requested permissions it works.  I am trying to use 'onedrive.appfolder offline_access'.  

I can't seem to figure out if this is an API change or a problem with my app configuration on Azure.  Does your library support these permissions?

Thank you,

David

**Comment by krizalys** [comment]
@davemaxg Normally, you pass your scope when calling `Client::getLogInUrl(array $scopes, $redirectUri, $state = null)`. Yes, the library supports the scope called `offline_access`, you can try using it, instead of `onedrive.appfolder offline_access`, I never tried this one if it exists.

If you are still having this issue, you may reopen and show us the code you are using.

Thanks.
